# Generated by Django 2.1.7 on 2019-03-23 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('bgg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_link', models.URLField()),
                ('thumbnail', models.URLField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('year_published', models.IntegerField()),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('playing_time', models.IntegerField()),
                ('minplay_time', models.IntegerField()),
                ('maxplay_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameCategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameFamily',
            fields=[
                ('family_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameMechanic',
            fields=[
                ('mechanic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameStatistics',
            fields=[
                ('board_game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='games.BoardGame')),
                ('avg_rating', models.FloatField()),
                ('bayesian_avg_rating', models.FloatField()),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='boardgame',
            name='boardgame_category',
            field=models.ManyToManyField(to='games.BoardGameCategory'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='boardgame_family',
            field=models.ManyToManyField(to='games.BoardGameFamily'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='boardgame_mechanic',
            field=models.ManyToManyField(to='games.BoardGameMechanic'),
        ),
        migrations.AddField(
            model_name='familyrank',
            name='bg_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.BoardGameStatistics'),
        ),
    ]
